<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Chan" ignored="2" name="Test(failed)" tests="2" failures="2" timestamp="12 Dec 2021 18:35:28 GMT" time="55.266" errors="0">
  <testcase name="cickOnSaveAndAllTheFillSareSaveOrNot" time="22.48" classname="com.crm.SDET26.opportunity.ClickOnSaveAndAllTheFillSareSaveOrNotTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.crm.SDET26.opportunity.ClickOnSaveAndAllTheFillSareSaveOrNotTest.cickOnSaveAndAllTheFillSareSaveOrNot(ClickOnSaveAndAllTheFillSareSaveOrNotTest.java:71)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- cickOnSaveAndAllTheFillSareSaveOrNot -->
  <testcase name="createOpportunitywithSalesStageClosedLost" time="12.611" classname="com.crm.SDET26.opportunity.CreateOpportunitywithSalesStageClosedLostTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Team Selling] but found [Team Selling  ]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Team Selling] but found [Team Selling  ]
at com.crm.SDET26.opportunity.CreateOpportunitywithSalesStageClosedLostTest.createOpportunitywithSalesStageClosedLost(CreateOpportunitywithSalesStageClosedLostTest.java:69)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- createOpportunitywithSalesStageClosedLost -->
  <testcase name="@BeforeSuite dataBaseConnection" time="0.0" classname="com.crm.SDET26.genericUtility.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite dataBaseConnection -->
  <testcase name="@AfterSuite disconnectDB" time="0.0" classname="com.crm.SDET26.genericUtility.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite disconnectDB -->
</testsuite> <!-- Test(failed) -->
